// <auto-generated />
namespace Nanobank.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addDateOfCreatingfieldtoComplainTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDateOfCreatingfieldtoComplainTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201712252203129_add DateOfCreating field to ComplainTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
